# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acountEditForm.ui'
#
# Created: Sat Jun 21 23:40:36 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccountEditFormDialog(object):
    def setupUi(self, AccountEditFormDialog):
        AccountEditFormDialog.setObjectName("AccountEditFormDialog")
        AccountEditFormDialog.resize(591, 323)
        self.buttonBox = QtWidgets.QDialogButtonBox(AccountEditFormDialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 280, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_2 = QtWidgets.QGroupBox(AccountEditFormDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 271, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 231, 231))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.userGroupLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.userGroupLabel.setObjectName("userGroupLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userGroupLabel)
        self.userGroupComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.userGroupComboBox.setObjectName("userGroupComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userGroupComboBox)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.roleComboBox.setObjectName("roleComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roleComboBox)
        self.accountEnabledLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.accountEnabledLabel.setObjectName("accountEnabledLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.accountEnabledLabel)
        self.accountEnabledCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.accountEnabledCheckBox.setObjectName("accountEnabledCheckBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.accountEnabledCheckBox)
        self.accountLockedLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.accountLockedLabel_2.setObjectName("accountLockedLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.accountLockedLabel_2)
        self.accountLockedCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.accountLockedCheckBox.setObjectName("accountLockedCheckBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.accountLockedCheckBox)
        self.accountExpiredLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.accountExpiredLabel.setObjectName("accountExpiredLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.accountExpiredLabel)
        self.accountExpiredCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.accountExpiredCheckBox.setObjectName("accountExpiredCheckBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.accountExpiredCheckBox)
        self.credentialsExpiredLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.credentialsExpiredLabel.setObjectName("credentialsExpiredLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.credentialsExpiredLabel)
        self.credentialsExpiredCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.credentialsExpiredCheckBox.setObjectName("credentialsExpiredCheckBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.credentialsExpiredCheckBox)
        self.departmentLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.departmentLabel.setObjectName("departmentLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.departmentLabel)
        self.departmentComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.departmentComboBox.setObjectName("departmentComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.departmentComboBox)
        self.groupBox = QtWidgets.QGroupBox(AccountEditFormDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 271, 261))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 231, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.userNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userNameLabel)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameLineEdit)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.genderLineEdit.setObjectName("genderLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.genderLineEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.ageLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit)
        self.phoneNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.phoneNumberLabel)
        self.phoneNumberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.phoneNumberLineEdit.setObjectName("phoneNumberLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phoneNumberLineEdit)
        self.emailLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.descriptionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.passwordAgainLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordAgainLabel.setObjectName("passwordAgainLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordAgainLabel)
        self.passwordAgainLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordAgainLineEdit.setObjectName("passwordAgainLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordAgainLineEdit)
        self.passwordHintLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordHintLabel.setObjectName("passwordHintLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordHintLabel)
        self.passwordHintLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordHintLineEdit.setObjectName("passwordHintLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordHintLineEdit)

        self.retranslateUi(AccountEditFormDialog)
        self.buttonBox.accepted.connect(AccountEditFormDialog.accept)
        self.buttonBox.rejected.connect(AccountEditFormDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AccountEditFormDialog)

    def retranslateUi(self, AccountEditFormDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountEditFormDialog.setWindowTitle(_translate("AccountEditFormDialog", "Account Edit Form"))
        self.groupBox_2.setTitle(_translate("AccountEditFormDialog", "Account properties"))
        self.userGroupLabel.setText(_translate("AccountEditFormDialog", "User group"))
        self.roleLabel.setText(_translate("AccountEditFormDialog", "Role"))
        self.accountEnabledLabel.setText(_translate("AccountEditFormDialog", "Account enabled"))
        self.accountLockedLabel_2.setText(_translate("AccountEditFormDialog", "Account locked"))
        self.accountExpiredLabel.setText(_translate("AccountEditFormDialog", "Account expired"))
        self.credentialsExpiredLabel.setText(_translate("AccountEditFormDialog", "Credentials expired"))
        self.departmentLabel.setText(_translate("AccountEditFormDialog", "Department"))
        self.groupBox.setTitle(_translate("AccountEditFormDialog", "User information"))
        self.userNameLabel.setText(_translate("AccountEditFormDialog", "User name"))
        self.genderLabel.setText(_translate("AccountEditFormDialog", "Gender"))
        self.ageLabel.setText(_translate("AccountEditFormDialog", "Age"))
        self.phoneNumberLabel.setText(_translate("AccountEditFormDialog", "Phone number"))
        self.emailLabel.setText(_translate("AccountEditFormDialog", "Email"))
        self.descriptionLabel.setText(_translate("AccountEditFormDialog", "Description"))
        self.passwordLabel.setText(_translate("AccountEditFormDialog", "Password"))
        self.passwordAgainLabel.setText(_translate("AccountEditFormDialog", "Password again"))
        self.passwordHintLabel.setText(_translate("AccountEditFormDialog", "Password hint"))

